create table if not exists public.cron_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  timezone text not null,
  current_hour integer not null,
  matched_profile_count integer not null default 0,
  dry_run boolean not null default false,
  jobs_scraped integer not null default 0,
  jobs_sent integer not null default 0,
  status text not null default 'running',
  errors jsonb not null default '[]'::jsonb
);

alter table public.cron_runs enable row level security;

create index if not exists idx_cron_runs_started_at
  on public.cron_runs (started_at desc);
